name: Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dependencies:
          - "lowest"
          - "highest"
        php:
          - "8.4"
          - "8.5"

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@2.37.0
        with:
          php-version: ${{ matrix.php }}
          extensions: intl, mbstring
          tools: "composer:v2"

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: "Install lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: composer update --prefer-lowest --no-interaction --no-progress --no-suggest ${{ matrix.composer-options }}

      - name: "Install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: composer update --no-interaction --no-progress --no-suggest ${{ matrix.composer-options }}

      - name: "Run tests"
        run: ./vendor/bin/phpunit -c phpunit.xml

  cs:
    name: Codestyle check on PHP 8.4
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@2.37.0
        with:
          php-version: 8.4

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Download dependencies
        run: composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable

      - name: Run tests
        run: ./vendor/bin/phpcs

  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - "8.4"

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@2.37.0
        with:
          php-version: ${{ matrix.php }}

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Download dependencies
        run: composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --memory-limit 512M
